### ISSUE TITLE
Error "can't convert String into Integer (TypeError)"

### ISSUE THREAD

**Issue by netandreus** [alexrothenberg/legacy_data#1]
I'm trying to convert this table to model:

CREATE TABLE IF NOT EXISTS `properties_predefined` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `key` varchar(255) DEFAULT NULL,
  `type` enum('text','document','asset','bool','select','object') DEFAULT NULL,
  `data` text,
  `config` text,
  `ctype` enum('document','asset','object') DEFAULT NULL,
  `inheritable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

and got this error: 

analyzing properties_predefined => PropertiesPredefined
/var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/legacy_data/schema.rb:138:in `[]=': can't convert String into Integer (TypeError)
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/legacy_data/schema.rb:138:in`constraints'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/legacy_data/schema.rb:138:in `each'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/legacy_data/schema.rb:138:in`constraints'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/legacy_data/schema.rb:76:in `analyze_table'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/legacy_data/schema.rb:22:in`analyze_table'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/legacy_data/schema.rb:9:in `analyze'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:18:in`generate_models_from_tables'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/shell.rb:14:in `map'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/core_ext/ordered_hash.rb:73:in`each'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/generators.rb:163:in `invoke'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/commands/generate.rb:10
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in `new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/commands.rb:17
    from script/rails:6:in`require'
    from script/rails:6

I;m using 0.2.0 version legacy_data with rails-3.0.1.
What can i do with it?

**Comment by alexrothenberg** [comment]
I'm still working on the 0.2.0 version with Rails 3 and as you have figured out its not quite ready.  The specs are all passing but it doesn't quite work when used as a generator inside a real rails project.  I hope to get that working soon and will leave this issue open until I do.

Sorry for the inconvenience.

**Comment by netandreus** [comment]
Thank you for your responce! We (Russian users of legacy_data) will be waiting for rails 3 support.

**Comment by alexrothenberg** [comment]
Released what I think is a Rails3 compatible version of this gem to rubygems.org as v0.2.0. Please do 'gem install legacy_data' and let me know if you face any issues using it.

I appreciate having Russian users of legacy_data :)

**Comment by netandreus** [comment]
Hello, Alex.
I do it, but got errors. Here is my log (I don't use factory girl):
root@vaio:~/Ruby/myapp# gem install legacy_data
Successfully installed activesupport-3.0.3
Successfully installed legacy_data-0.2.0
Successfully installed activemodel-3.0.3
Successfully installed actionpack-3.0.3
Successfully installed arel-2.0.6
5 gems installed
Installing ri documentation for activesupport-3.0.3...
Installing ri documentation for legacy_data-0.2.0...
Installing ri documentation for activemodel-3.0.3...
Installing ri documentation for actionpack-3.0.3...
Installing ri documentation for arel-2.0.6...
Installing RDoc documentation for activesupport-3.0.3...
Installing RDoc documentation for legacy_data-0.2.0...
Installing RDoc documentation for activemodel-3.0.3...
Installing RDoc documentation for actionpack-3.0.3...
Installing RDoc documentation for arel-2.0.6...
root@vaio:~/Ruby/myapp# rails generate models_from_tables
analyzing pma_bookmark => PmaBookmark
analyzing pma_column_info => PmaColumnInfo
analyzing pma_designer_coords => PmaDesignerCoord
analyzing pma_history => PmaHistory
analyzing pma_pdf_pages => PmaPdfPage
analyzing pma_relation => PmaRelation
analyzing pma_table_coords => PmaTableCoord
analyzing pma_table_info => PmaTableInfo
analyzing pma_tracking => PmaTracking
Done analyzing the tables.  
  Automatic class names written to '/home/andrey/Ruby/myapp/app/models/table_mappings.yml'
  Since the database probably does not follow Rails naming conventions you should take a look at the class names and update them in that file. 
  Once you're done hit <enter> to continue generating the models"

   identical  app/models/pma_bookmark.rb
/var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:42:in `initialize': No such file or directory - /home/andrey/Ruby/myapp/spec/factories.rb (Errno::ENOENT)
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:42:in`open'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:42:in `add_factory_girl_factory'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:32:in`generate_models_from_tables'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:25:in `each'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:25:in`generate_models_from_tables'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/shell.rb:14:in `map'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/core_ext/ordered_hash.rb:73:in`each'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/generators.rb:163:in `invoke'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/commands/generate.rb:10
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in `new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/commands.rb:17
    from script/rails:6:in`require'
    from script/rails:6
root@vaio:~/Ruby/myapp# 
What's wrong?

**Comment by alexrothenberg** [comment]
I think you're still using the version checked out from github (I see this in your stack trace /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769)

Try "gem uninstall legacy_data" then "gem list" to make sure its gone then "gem install legacy_data" to get the published version from rubygems.org.

Hopefully that will fix it.

**Comment by netandreus** [comment]
Yes, you're right! I specified old version in my gemgile. Old error is gone, but now I have new :-(

analyzing dao_acl => DaoAcl
/var/lib/gems/1.8/gems/legacy_data-0.2.0/lib/legacy_data/schema.rb:138:in `[]=': can't convert String into Integer (TypeError)
    from /var/lib/gems/1.8/gems/legacy_data-0.2.0/lib/legacy_data/schema.rb:138:in`constraints'
    from /var/lib/gems/1.8/gems/legacy_data-0.2.0/lib/legacy_data/schema.rb:138:in `each'
    from /var/lib/gems/1.8/gems/legacy_data-0.2.0/lib/legacy_data/schema.rb:138:in`constraints'
    from /var/lib/gems/1.8/gems/legacy_data-0.2.0/lib/legacy_data/schema.rb:76:in `analyze_table'
    from /var/lib/gems/1.8/gems/legacy_data-0.2.0/lib/legacy_data/schema.rb:22:in`analyze_table'
    from /var/lib/gems/1.8/gems/legacy_data-0.2.0/lib/legacy_data/schema.rb:9:in `analyze'
    from /var/lib/gems/1.8/gems/legacy_data-0.2.0/lib/generators/models_from_tables/models_from_tables_generator.rb:18:in`generate_models_from_tables'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/shell.rb:14:in `map'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/core_ext/ordered_hash.rb:73:in`each'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/generators.rb:163:in `invoke'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/commands/generate.rb:10
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in `new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/commands.rb:17
    from script/rails:6:in`require'
    from script/rails:6

**Comment by alexrothenberg** [comment]
Andrey,

It looks like your dao_acl has a boolean non-nullable column and I'm guessing you're using a database other than mysql, sqlite or oracle (which I have tested with).  

I just pushed a new version 0.2.1 that should fix the bug you found.  Hopefully it will work for you this time

**Comment by netandreus** [comment]
Yes, your update fix this bug! I am using mysql. All models created. Thank you, Alex!
