### ISSUE TITLE
No such file or directory - /home/andrey/Ruby/myapp/spec/factories.rb (Errno::ENOENT)

### ISSUE THREAD

**Issue by netandreus** [alexrothenberg/legacy_data#2]
I am got an error:
create  app/models/pma_bookmark.rb
/var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:42:in `initialize': No such file or directory - /home/andrey/Ruby/myapp/spec/factories.rb (Errno::ENOENT)
when trying to create model from table "pma_bookmark" of PhpMyAdmin.

**Comment by alexrothenberg** [comment]
By default it assumes you are using FactoryGirl and RSpec so tries to create some factories in a home/andrey/Ruby/myapp/spec/factories.rb file.  You can avoid this error by either creating a spec folder in your project or running the generator without the '--with-factories' option.

I'll look into adding a fix so warns you it cannot create factories when no spec folder exists.  Or you could fork, make the change and submit a pull request if you like.

**Comment by netandreus** [comment]
I doesn't use factiry girl. Just do rails new testapp -d=mysql and configure database.yml

**Comment by alexrothenberg** [comment]
Updated the generator to not create a factories.rb file (or give the error above) when your project does not have a spec directory.

Released to rubygems.org as v0.2.0.  Please do 'gem install legacy_data' and let me know if you still face any issues.  Closing this issue.

**Comment by netandreus** [comment]
root@vaio:~/Ruby/myapp# gem install legacy_data
Successfully installed activesupport-3.0.3
Successfully installed legacy_data-0.2.0
Successfully installed activemodel-3.0.3
Successfully installed actionpack-3.0.3
Successfully installed arel-2.0.6
5 gems installed
Installing ri documentation for activesupport-3.0.3...
Installing ri documentation for legacy_data-0.2.0...
Installing ri documentation for activemodel-3.0.3...
Installing ri documentation for actionpack-3.0.3...
Installing ri documentation for arel-2.0.6...
Installing RDoc documentation for activesupport-3.0.3...
Installing RDoc documentation for legacy_data-0.2.0...
Installing RDoc documentation for activemodel-3.0.3...
Installing RDoc documentation for actionpack-3.0.3...
Installing RDoc documentation for arel-2.0.6...
root@vaio:~/Ruby/myapp# rails generate models_from_tables
analyzing pma_bookmark => PmaBookmark
analyzing pma_column_info => PmaColumnInfo
analyzing pma_designer_coords => PmaDesignerCoord
analyzing pma_history => PmaHistory
analyzing pma_pdf_pages => PmaPdfPage
analyzing pma_relation => PmaRelation
analyzing pma_table_coords => PmaTableCoord
analyzing pma_table_info => PmaTableInfo
analyzing pma_tracking => PmaTracking
Done analyzing the tables.  
  Automatic class names written to '/home/andrey/Ruby/myapp/app/models/table_mappings.yml'
  Since the database probably does not follow Rails naming conventions you should take a look at the class names and update them in that file. 
  Once you're done hit <enter> to continue generating the models"

   identical  app/models/pma_bookmark.rb
/var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:42:in `initialize': No such file or directory - /home/andrey/Ruby/myapp/spec/factories.rb (Errno::ENOENT)
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:42:in`open'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:42:in `add_factory_girl_factory'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:32:in`generate_models_from_tables'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:25:in `each'
    from /var/lib/gems/1.8/bundler/gems/legacy_data-e64935f75769/lib/generators/models_from_tables/models_from_tables_generator.rb:25:in`generate_models_from_tables'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/shell.rb:14:in `map'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/core_ext/ordered_hash.rb:73:in`each'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
    from /var/lib/gems/1.8/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/generators.rb:163:in `invoke'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/commands/generate.rb:10
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in `new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/commands.rb:17
    from script/rails:6:in`require'
    from script/rails:6
root@vaio:~/Ruby/myapp#
