### ISSUE TITLE
rails 3 issue (w/ bundler)

### ISSUE THREAD

**Issue by ppetrick** [alexrothenberg/legacy_data#3]
when attempting rails generate models_from_tables, i get this error:
"The 'matthuhiggins-foreigner' gem has changed names to 'foreigner'"
"Install the renamed gem using 'gem install foreigner'"

I have foreigner installed, but it looks like your gem dependencies are set up to use matthuhiggins-foreigner

**Comment by alexrothenberg** [comment]
Yes version 0.2.x does work with Rails3.  Are you using the latest version of the legacy_data?

The Rails 2 version did depend on matthuhiggins-foreigner but I changed that in the 0.2.1 version and have used it successfully.

Let me know if you're having this trouble with the latest version and I'll try to figure out what's going on.

**Comment by ppetrick** [comment]
ahh, i was using rails 3.0.0 so bundler was grabbing a pre-.0.2.x version. thanks!
